apiVersion: v1
kind: Pod
metadata:
  name: kubectl-go-test
  namespace: podinfo
spec:
  containers:
  - name: kubectl-go-container
    image: bitnami/kubectl:latest # Replace with an image containing both kubectl and Go if available
    command: ["sleep", "infinity"]
    # volumeMounts:
    # - mountPath: /root/.kube
    #   name: kubeconfig-volume
  serviceAccountName: limited-sa # Bind the ServiceAccount to the pod
  # volumes:
  # - name: kubeconfig-volume
  #   configMap:
  #     name: kubeconfig-configmap # Create this ConfigMap to provide kubeconfig (see below)
  # restartPolicy: Never