apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: podinfo
  name: limited-rolebinding
subjects:
  - kind: ServiceAccount
    name: limited-sa
    namespace: podinfo
roleRef:
  kind: Role
  name: limited-role
  apiGroup: rbac.authorization.k8s.io
