apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: podinfo
  name: limited-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "watch"] # only list is required when using the poll method
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["list"]
